#!/bin/bash
python3 train_gaussian.py --dataset gaussian500 --k 1 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 2 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 3 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 4 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 5 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 6 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 7 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 8 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 9 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 10 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 11 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 12 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 13 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 14 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 15 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 16 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 17 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 18 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 19 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 20 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 21 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 22 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 23 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 24 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 25 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 26 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 27 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 28 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 29 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 30 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 31 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 32 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 33 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 34 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 35 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 36 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 37 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 38 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 39 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000
python3 train_gaussian.py --dataset gaussian500 --k 40 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 250000

python3 train_gaussian.py --dataset gaussian600 --k 1 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 2 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 3 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 4 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 5 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 6 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 7 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 8 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 9 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 10 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 11 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 12 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 13 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 14 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 15 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 16 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 17 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 18 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 19 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 20 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 21 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 22 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 23 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 24 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 25 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 26 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 27 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 28 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 29 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 30 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 31 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 32 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 33 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 34 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 35 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 36 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 37 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 38 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 39 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000
python3 train_gaussian.py --dataset gaussian600 --k 40 --outfile results/ablation_study_values_of_k.csv --batch_size 64 --num_tuples 360000

