#!/bin/bash
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 10000 --regime independent --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 500 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 1000 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 1500 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 2000 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 2500 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 3000 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 3500 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 4000 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 5000 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 5500 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 6000 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 6500 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 7000 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 7500 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 8000 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 8500 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 9000 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 9500 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 10000 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 10500 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 11000 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 11500 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 12000 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 12500 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 13000 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 13500 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 14000 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 14500 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 15000 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 15500 --regime subsample --train_loss_thresh 0.01
python3 train.py --dataset cifar100 --k 2 --outfile results/ablation_study_iid_vs_noniid_cifar.csv --batch_size 10 --M 16000 --regime subsample --train_loss_thresh 0.01
