#!/bin/bash
#python3 train_cls.py --dataset mnist --outfile results/ablation_study_iid_vs_noniid_mnist_only_cls.csv --batch_size 10 --num_train 30000 
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 10000 --regime independent --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 500 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 1000 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 1500 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 2000 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 2500 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 3000 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 3500 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 4000 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 5000 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 5500 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 6000 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 6500 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 7000 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 7500 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 8000 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 8500 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 9000 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 9500 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 10000 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 10500 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 11000 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 11500 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 12000 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 12500 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 13000 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 13500 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 14000 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 14500 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 15000 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 15500 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 16000 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 16500 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 17000 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 17500 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 18000 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 18500 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 19000 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 19500 --regime subsample --train_loss_thresh 0.001
#python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 20000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 30000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 40000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 50000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 60000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 70000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 80000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 90000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 100000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 110000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 120000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 130000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 140000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 150000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 160000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 170000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 180000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 190000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 200000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 210000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 220000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 230000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 240000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 250000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 260000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 270000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 280000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 290000 --regime subsample --train_loss_thresh 0.001
python3 train.py --dataset mnist --k 3 --outfile results/ablation_study_iid_vs_noniid_mnist.csv --batch_size 10 --M 300000 --regime subsample --train_loss_thresh 0.001
